name: Deploy Blue-Green React App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2 Configurar SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3 Deploy Blue
      - name: Deploy Blue container
        run: ssh deployer@TU_IP "bash ~/scripts/deploy_blue.sh"

      # 4 Cambiar tráfico a Blue
      - name: Switch Nginx to Blue
        run: ssh deployer@TU_IP "bash ~/scripts/switch.sh blue"

      # 5 (Opcional) Deploy Green
      - name: Deploy Green container
        if: github.ref == 'refs/heads/main'
        run: ssh deployer@TU_IP "bash ~/scripts/deploy_green.sh"

      # 6 (Opcional) Cambiar tráfico a Green
      # - name: Switch Nginx to Green
      #   run: ssh deployer@TU_IP "bash ~/scripts/switch.sh green"
